/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingServicesRouteImport } from './routes/_marketing/services'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingBlogRouteImport } from './routes/_marketing/blog'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as MarketingCaseStudiesRouteRouteImport } from './routes/_marketing/case-studies/route'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MarketingCaseStudiesWebsitesRouteImport } from './routes/_marketing/case-studies/websites'
import { Route as MarketingCaseStudiesHybridMeetingSolutionsRouteImport } from './routes/_marketing/case-studies/hybrid-meeting-solutions'

const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingServicesRoute = MarketingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingBlogRoute = MarketingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const MarketingCaseStudiesRouteRoute =
  MarketingCaseStudiesRouteRouteImport.update({
    id: '/case-studies',
    path: '/case-studies',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCaseStudiesWebsitesRoute =
  MarketingCaseStudiesWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => MarketingCaseStudiesRouteRoute,
  } as any)
const MarketingCaseStudiesHybridMeetingSolutionsRoute =
  MarketingCaseStudiesHybridMeetingSolutionsRouteImport.update({
    id: '/hybrid-meeting-solutions',
    path: '/hybrid-meeting-solutions',
    getParentRoute: () => MarketingCaseStudiesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/case-studies': typeof MarketingCaseStudiesRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/about': typeof MarketingAboutRoute
  '/blog': typeof MarketingBlogRoute
  '/contact': typeof MarketingContactRoute
  '/services': typeof MarketingServicesRoute
  '/case-studies/hybrid-meeting-solutions': typeof MarketingCaseStudiesHybridMeetingSolutionsRoute
  '/case-studies/websites': typeof MarketingCaseStudiesWebsitesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/case-studies': typeof MarketingCaseStudiesRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/about': typeof MarketingAboutRoute
  '/blog': typeof MarketingBlogRoute
  '/contact': typeof MarketingContactRoute
  '/services': typeof MarketingServicesRoute
  '/case-studies/hybrid-meeting-solutions': typeof MarketingCaseStudiesHybridMeetingSolutionsRoute
  '/case-studies/websites': typeof MarketingCaseStudiesWebsitesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_marketing/case-studies': typeof MarketingCaseStudiesRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/blog': typeof MarketingBlogRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/services': typeof MarketingServicesRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/case-studies/hybrid-meeting-solutions': typeof MarketingCaseStudiesHybridMeetingSolutionsRoute
  '/_marketing/case-studies/websites': typeof MarketingCaseStudiesWebsitesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/case-studies'
    | '/login'
    | '/signup'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/case-studies/hybrid-meeting-solutions'
    | '/case-studies/websites'
    | '/api/auth/$'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-studies'
    | '/login'
    | '/signup'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/case-studies/hybrid-meeting-solutions'
    | '/case-studies/websites'
    | '/api/auth/$'
    | '/app'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_marketing'
    | '/_auth/app'
    | '/_marketing/case-studies'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_marketing/about'
    | '/_marketing/blog'
    | '/_marketing/contact'
    | '/_marketing/services'
    | '/_marketing/'
    | '/_marketing/case-studies/hybrid-meeting-solutions'
    | '/_marketing/case-studies/websites'
    | '/api/auth/$'
    | '/_auth/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/services': {
      id: '/_marketing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MarketingServicesRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/blog': {
      id: '/_marketing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof MarketingBlogRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_marketing/case-studies': {
      id: '/_marketing/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof MarketingCaseStudiesRouteRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/case-studies/websites': {
      id: '/_marketing/case-studies/websites'
      path: '/websites'
      fullPath: '/case-studies/websites'
      preLoaderRoute: typeof MarketingCaseStudiesWebsitesRouteImport
      parentRoute: typeof MarketingCaseStudiesRouteRoute
    }
    '/_marketing/case-studies/hybrid-meeting-solutions': {
      id: '/_marketing/case-studies/hybrid-meeting-solutions'
      path: '/hybrid-meeting-solutions'
      fullPath: '/case-studies/hybrid-meeting-solutions'
      preLoaderRoute: typeof MarketingCaseStudiesHybridMeetingSolutionsRouteImport
      parentRoute: typeof MarketingCaseStudiesRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface MarketingCaseStudiesRouteRouteChildren {
  MarketingCaseStudiesHybridMeetingSolutionsRoute: typeof MarketingCaseStudiesHybridMeetingSolutionsRoute
  MarketingCaseStudiesWebsitesRoute: typeof MarketingCaseStudiesWebsitesRoute
}

const MarketingCaseStudiesRouteRouteChildren: MarketingCaseStudiesRouteRouteChildren =
  {
    MarketingCaseStudiesHybridMeetingSolutionsRoute:
      MarketingCaseStudiesHybridMeetingSolutionsRoute,
    MarketingCaseStudiesWebsitesRoute: MarketingCaseStudiesWebsitesRoute,
  }

const MarketingCaseStudiesRouteRouteWithChildren =
  MarketingCaseStudiesRouteRoute._addFileChildren(
    MarketingCaseStudiesRouteRouteChildren,
  )

interface MarketingRouteRouteChildren {
  MarketingCaseStudiesRouteRoute: typeof MarketingCaseStudiesRouteRouteWithChildren
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingBlogRoute: typeof MarketingBlogRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingServicesRoute: typeof MarketingServicesRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingCaseStudiesRouteRoute: MarketingCaseStudiesRouteRouteWithChildren,
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingBlogRoute: MarketingBlogRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingServicesRoute: MarketingServicesRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
